name: JavaScript

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
  pull_request:
    paths:
      - "**.js"
  workflow_dispatch:

jobs:
  syntax:
    name: "Check Syntax"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/checkout@v4
      - run: echo "::add-matcher::.github/javascript-syntax.json"
      - name: Remove files to be ignored
        run: |
          true
      - run: |
          ! find wcfsetup/ -type f -name '*.js' -exec node -c '{}' \; 2>&1 \
            |awk 'BEGIN {m=0} /(.js):[0-9]+$/ {m=1; printf "%s - ",$0} m==1 && /^SyntaxError/ { m=0; print }' \
            |sed "s@$(pwd)@.@" \
            |grep '^'
