name: TypeScript

on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
  pull_request:
    paths:
      - "**.ts"
  workflow_dispatch:

jobs:
  tsc:
    name: "TSC"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm install
      - run: |
          npx tsc --noEmit
  eslint:
    name: "eslint"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm install
      - run: npx eslint .
  javascript_sync:
    name: "Check for outdated JavaScript"
    needs: tsc
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm install
      - run: rm -rf files/js/SoftCreatR/
      - run: rm -rf files/js/MysteryCode/
      - run: |
          npx tsc
      - run: echo "::add-matcher::.github/diff.json"
      - name: Show diff
        run: |
          git checkout -- package-lock.json
          git diff --exit-code
